name: Format Script Blocks

on:
  push:
    branches: [main, dev]
    paths:
      - 'data/blocks/**'
      - 'chores/formatBlocks.py'
  pull_request:
    branches: [main, dev]
    paths:
      - 'data/blocks/**'
      - 'chores/formatBlocks.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
          
      - name: Install dependencies
        run: |
          pip install pyyaml
          pip install m2r
          
      - name: Run formatBlocks
        run: python chores/formatBlocks.py

      - name: Run generateDocs
        run: python chores/generateDocs.py
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add out/scriptBlocks.json
          git add docs
          git diff --quiet && git diff --staged --quiet || (git commit -m "CHORE: format scriptBlocks.json" && git push)