name: Format Script Blocks

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  pull_request:
    branches: [main, dev]
    paths:
      - 'data/blocks/**'
      - 'src/formatBlocks.py'
      - 'src/sortItemParameters.py'
      - '.github/workflows/format-blocks.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
          
      - name: Install dependencies
        run: |
          pip install .

      - name: Run formatBlocks
        run: python src/formatBlocks.py
      - name: Run sortItemParameters
        run: python src/sortItemParameters.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add out/scriptBlocks.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "CHORE: format scriptBlocks.json" && git push)